language: java
install: true
jdk:
    - oraclejdk7
script: mvn clean install -Prun-its
after_failure: cat /home/travis/build/odavid/maven-plugins/attach-report-maven-plugin/target/it/simple-it/build.log 
